public class Main
{
    public static void main(String[] args)
    {
        // Builds the original data
        DataBuilder dataBuilder = new DataBuilder();
        dataBuilder.run();

        // Salts the data generated by the data builder
        Salter salter = new Salter();
        salter.run();

        // Smooths the data generated by the salter
        Smoother smoother = new Smoother();
        smoother.run();
    }
}