import java.io.*;
import java.util.Random;
import java.util.Scanner;

public class Salter
{
    private static final Random random = new Random();
    private static final Scanner scanner = new Scanner(System.in);
    private int variability;

    // Constructor to initialize variability with user input or default value
    // If the input is invalid or none is provided, it will use the default value of 10
    public Salter()
    {
        System.out.print("\nEnter variability (or press Enter for default value of 10): ");
        String input = scanner.nextLine().trim();
        
        if (input.isEmpty())
        {
            this.variability = 10;
            System.out.println("Using default variability: 10");
        }
        else
        {
            try
            {
                this.variability = Integer.parseInt(input);
            }
            catch (NumberFormatException e)
            {
                System.out.println("Invalid input. Using default variability: 10");
                this.variability = 10;
            }
        }
    }

    // Main method to run the Salter
    public void run()
    {
        salt();
    }   
    
    // Reads the data generated by the DataBuilder from a CSV file, salts (adds noise to) the y-values, and writes the
    // salted data to a new CSV file.
    private void salt()
    {
        try
        {
            BufferedReader bufferedReader = new BufferedReader(new FileReader("11. Plotter Salter Smoother - Original/output/data.csv"));
            FileWriter fileWriter = new FileWriter("11. Plotter Salter Smoother - Original/output/salted_data.csv");
            String line = bufferedReader.readLine();
            System.out.println("Salting data with variability of " + variability + "...");

            fileWriter.append("x,y\n");
            while ((line = bufferedReader.readLine()) != null)
            {
                // Given the data is in the format "x,y", we split the line by the comma and parse the values
                String[] values = line.split(",");
                double x = Double.parseDouble(values[0]);
                double y = Double.parseDouble(values[1]);

                // Add noise to the y-value based on the variability
                y += random.nextInt(-variability, variability);

                // Write the salted data to the new CSV file
                fileWriter.append(x + "," + y + "\n");
            }
            System.out.println("Salting complete, data saved to output/salted_data.csv");
            bufferedReader.close();
            fileWriter.close();
        }
        catch (Exception exception)
        {
            System.out.println(exception);
        }
    }
}
